/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Billing;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Lenovo
 */
public class BillingSystem extends javax.swing.JFrame {

      String operations;
      String answers;
      double firstnum,secondnum,result;
    /**
     * Creates new form BillingSystem
     */
    public BillingSystem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtDisplay = new javax.swing.JTextField();
        b8 = new javax.swing.JButton();
        b7 = new javax.swing.JButton();
        badd = new javax.swing.JButton();
        b9 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        bsub = new javax.swing.JButton();
        b1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        bmul = new javax.swing.JButton();
        bans = new javax.swing.JButton();
        bdot = new javax.swing.JButton();
        bmod = new javax.swing.JButton();
        bdiv = new javax.swing.JButton();
        b0 = new javax.swing.JButton();
        bclear = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1150, 850));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(125, 231, 165));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.setPreferredSize(new java.awt.Dimension(330, 360));
        jPanel1.setLayout(null);

        txtDisplay.setEditable(false);
        txtDisplay.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jPanel1.add(txtDisplay);
        txtDisplay.setBounds(10, 6, 310, 60);

        b8.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        b8.setText("8");
        b8.setPreferredSize(new java.awt.Dimension(60, 50));
        b8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8ActionPerformed(evt);
            }
        });
        jPanel1.add(b8);
        b8.setBounds(100, 70, 60, 50);

        b7.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        b7.setText("7");
        b7.setPreferredSize(new java.awt.Dimension(60, 50));
        b7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b7ActionPerformed(evt);
            }
        });
        jPanel1.add(b7);
        b7.setBounds(20, 70, 60, 50);

        badd.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        badd.setText("+");
        badd.setPreferredSize(new java.awt.Dimension(60, 50));
        badd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baddActionPerformed(evt);
            }
        });
        jPanel1.add(badd);
        badd.setBounds(260, 70, 60, 50);

        b9.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        b9.setText("9");
        b9.setPreferredSize(new java.awt.Dimension(60, 50));
        b9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b9ActionPerformed(evt);
            }
        });
        jPanel1.add(b9);
        b9.setBounds(180, 70, 60, 50);

        b4.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        b4.setText("4");
        b4.setPreferredSize(new java.awt.Dimension(60, 50));
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });
        jPanel1.add(b4);
        b4.setBounds(20, 130, 60, 50);

        b5.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        b5.setText("5");
        b5.setPreferredSize(new java.awt.Dimension(60, 50));
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });
        jPanel1.add(b5);
        b5.setBounds(100, 130, 60, 50);

        b6.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        b6.setText("6");
        b6.setPreferredSize(new java.awt.Dimension(60, 50));
        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });
        jPanel1.add(b6);
        b6.setBounds(180, 130, 60, 50);

        bsub.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        bsub.setText("-");
        bsub.setPreferredSize(new java.awt.Dimension(60, 50));
        bsub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsubActionPerformed(evt);
            }
        });
        jPanel1.add(bsub);
        bsub.setBounds(260, 130, 60, 50);

        b1.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        b1.setText("1");
        b1.setPreferredSize(new java.awt.Dimension(60, 50));
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        jPanel1.add(b1);
        b1.setBounds(20, 190, 60, 50);

        b2.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        b2.setText("2");
        b2.setPreferredSize(new java.awt.Dimension(60, 50));
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        jPanel1.add(b2);
        b2.setBounds(100, 190, 60, 50);

        b3.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        b3.setText("3");
        b3.setPreferredSize(new java.awt.Dimension(60, 50));
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });
        jPanel1.add(b3);
        b3.setBounds(180, 190, 60, 50);

        bmul.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        bmul.setText("*");
        bmul.setPreferredSize(new java.awt.Dimension(60, 50));
        bmul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bmulActionPerformed(evt);
            }
        });
        jPanel1.add(bmul);
        bmul.setBounds(260, 190, 60, 50);

        bans.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        bans.setText("=");
        bans.setPreferredSize(new java.awt.Dimension(60, 50));
        bans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bansActionPerformed(evt);
            }
        });
        jPanel1.add(bans);
        bans.setBounds(180, 310, 140, 40);

        bdot.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        bdot.setText(".");
        bdot.setPreferredSize(new java.awt.Dimension(60, 50));
        bdot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdotActionPerformed(evt);
            }
        });
        jPanel1.add(bdot);
        bdot.setBounds(100, 250, 60, 50);

        bmod.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        bmod.setText("%");
        bmod.setPreferredSize(new java.awt.Dimension(60, 50));
        bmod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bmodActionPerformed(evt);
            }
        });
        jPanel1.add(bmod);
        bmod.setBounds(180, 250, 60, 50);

        bdiv.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        bdiv.setText("/");
        bdiv.setPreferredSize(new java.awt.Dimension(60, 50));
        bdiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdivActionPerformed(evt);
            }
        });
        jPanel1.add(bdiv);
        bdiv.setBounds(260, 250, 60, 50);

        b0.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        b0.setText("0");
        b0.setPreferredSize(new java.awt.Dimension(60, 50));
        b0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b0ActionPerformed(evt);
            }
        });
        jPanel1.add(b0);
        b0.setBounds(20, 250, 60, 50);

        bclear.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        bclear.setText("CE");
        bclear.setPreferredSize(new java.awt.Dimension(60, 50));
        bclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bclearActionPerformed(evt);
            }
        });
        jPanel1.add(bclear);
        bclear.setBounds(20, 310, 140, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(15, 120, 330, 360);

        jPanel2.setBackground(new java.awt.Color(220, 250, 253));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel2.setPreferredSize(new java.awt.Dimension(830, 370));
        jPanel2.setLayout(null);

        jCheckBox1.setFont(new java.awt.Font("Calibri", 1, 22)); // NOI18N
        jCheckBox1.setText("Biscuits");
        jCheckBox1.setPreferredSize(new java.awt.Dimension(125, 35));
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel2.add(jCheckBox1);
        jCheckBox1.setBounds(20, 280, 100, 40);

        jCheckBox2.setFont(new java.awt.Font("Calibri", 1, 22)); // NOI18N
        jCheckBox2.setText("Burger");
        jCheckBox2.setPreferredSize(new java.awt.Dimension(125, 35));
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });
        jPanel2.add(jCheckBox2);
        jCheckBox2.setBounds(20, 40, 100, 29);

        jCheckBox3.setFont(new java.awt.Font("Calibri", 1, 22)); // NOI18N
        jCheckBox3.setText("Coffee");
        jCheckBox3.setPreferredSize(new java.awt.Dimension(125, 35));
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });
        jPanel2.add(jCheckBox3);
        jCheckBox3.setBounds(20, 100, 100, 29);

        jCheckBox4.setFont(new java.awt.Font("Calibri", 1, 22)); // NOI18N
        jCheckBox4.setText("Noodle");
        jCheckBox4.setPreferredSize(new java.awt.Dimension(125, 35));
        jCheckBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox4ActionPerformed(evt);
            }
        });
        jPanel2.add(jCheckBox4);
        jCheckBox4.setBounds(20, 160, 100, 29);

        jCheckBox5.setFont(new java.awt.Font("Calibri", 1, 22)); // NOI18N
        jCheckBox5.setText("Chips");
        jCheckBox5.setPreferredSize(new java.awt.Dimension(125, 35));
        jCheckBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox5ActionPerformed(evt);
            }
        });
        jPanel2.add(jCheckBox5);
        jCheckBox5.setBounds(20, 220, 100, 29);

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Calibri", 1, 22)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("0");
        jPanel2.add(jTextField1);
        jTextField1.setBounds(120, 280, 70, 33);

        jTextField2.setEditable(false);
        jTextField2.setFont(new java.awt.Font("Calibri", 1, 22)); // NOI18N
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("0");
        jPanel2.add(jTextField2);
        jTextField2.setBounds(120, 40, 70, 33);

        jTextField3.setEditable(false);
        jTextField3.setFont(new java.awt.Font("Calibri", 1, 22)); // NOI18N
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setText("0");
        jPanel2.add(jTextField3);
        jTextField3.setBounds(120, 100, 70, 33);

        jTextField4.setEditable(false);
        jTextField4.setFont(new java.awt.Font("Calibri", 1, 22)); // NOI18N
        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField4.setText("0");
        jPanel2.add(jTextField4);
        jTextField4.setBounds(120, 160, 70, 33);

        jTextField5.setEditable(false);
        jTextField5.setFont(new java.awt.Font("Calibri", 1, 22)); // NOI18N
        jTextField5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField5.setText("0");
        jPanel2.add(jTextField5);
        jTextField5.setBounds(120, 220, 70, 33);

        jPanel3.setBackground(new java.awt.Color(176, 160, 252));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel3.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 30)); // NOI18N
        jLabel1.setText("Total Cost of Delivery");
        jPanel3.add(jLabel1);
        jLabel1.setBounds(10, 70, 280, 60);

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 30)); // NOI18N
        jLabel2.setText("Total Cost of Items");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(10, 10, 240, 60);

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 30)); // NOI18N
        jLabel3.setText("SGST");
        jLabel3.setFocusable(false);
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel3.add(jLabel3);
        jLabel3.setBounds(80, 220, 170, 50);

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 30)); // NOI18N
        jLabel4.setText("Total Cost of Mileage");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(10, 130, 270, 60);

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 30)); // NOI18N
        jLabel6.setText("CGST");
        jLabel6.setFocusable(false);
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel3.add(jLabel6);
        jLabel6.setBounds(80, 280, 170, 40);

        jTextField6.setEditable(false);
        jTextField6.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jTextField6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField6.setText("0");
        jPanel3.add(jTextField6);
        jTextField6.setBounds(310, 270, 120, 36);

        jTextField7.setEditable(false);
        jTextField7.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jTextField7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField7.setText("0");
        jPanel3.add(jTextField7);
        jTextField7.setBounds(310, 20, 120, 36);

        jTextField8.setEditable(false);
        jTextField8.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jTextField8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField8.setText("0");
        jPanel3.add(jTextField8);
        jTextField8.setBounds(310, 80, 120, 36);

        jTextField9.setEditable(false);
        jTextField9.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jTextField9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField9.setText("0");
        jPanel3.add(jTextField9);
        jTextField9.setBounds(310, 140, 120, 36);

        jTextField10.setEditable(false);
        jTextField10.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jTextField10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField10.setText("0");
        jPanel3.add(jTextField10);
        jTextField10.setBounds(310, 220, 120, 36);

        jPanel2.add(jPanel3);
        jPanel3.setBounds(200, 20, 435, 330);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(350, 120, 710, 370);

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.setPreferredSize(new java.awt.Dimension(1250, 110));
        jPanel4.setLayout(null);

        jLabel5.setBackground(new java.awt.Color(56, 33, 67));
        jLabel5.setFont(new java.awt.Font("Calibri", 1, 40)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(141, 138, 136));
        jLabel5.setText("Total Amount");
        jPanel4.add(jLabel5);
        jLabel5.setBounds(280, 150, 240, 80);

        jLabel7.setBackground(new java.awt.Color(56, 33, 67));
        jLabel7.setFont(new java.awt.Font("Calibri", 1, 40)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(141, 138, 136));
        jLabel7.setText("Sub Total");
        jPanel4.add(jLabel7);
        jLabel7.setBounds(280, 10, 240, 80);

        jLabel8.setBackground(new java.awt.Color(56, 33, 67));
        jLabel8.setFont(new java.awt.Font("Calibri", 1, 40)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(141, 138, 136));
        jLabel8.setText("Total Tax");
        jPanel4.add(jLabel8);
        jLabel8.setBounds(280, 80, 240, 80);

        jTextField11.setEditable(false);
        jTextField11.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jTextField11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField11.setText("Rs 0.0");
        jPanel4.add(jTextField11);
        jTextField11.setBounds(530, 160, 230, 60);

        jTextField12.setEditable(false);
        jTextField12.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jTextField12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField12.setText("Rs 0.0");
        jPanel4.add(jTextField12);
        jTextField12.setBounds(530, 20, 230, 60);

        jTextField13.setEditable(false);
        jTextField13.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jTextField13.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField13.setText("Rs 0.0");
        jPanel4.add(jTextField13);
        jTextField13.setBounds(530, 90, 230, 60);

        jButton1.setFont(new java.awt.Font("Calibri", 1, 34)); // NOI18N
        jButton1.setText("CALCULATE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1);
        jButton1.setBounds(830, 130, 200, 60);

        jButton2.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jButton2.setText("CLEAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2);
        jButton2.setBounds(830, 70, 200, 50);

        jPanel5.setBackground(new java.awt.Color(56, 33, 67));
        jPanel5.setLayout(null);

        jLabel11.setFont(new java.awt.Font("Calibri", 1, 30)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 0));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Burger          80/-");
        jPanel5.add(jLabel11);
        jLabel11.setBounds(10, 80, 250, 37);

        jLabel12.setFont(new java.awt.Font("Calibri", 1, 30)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 0));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Biscuits        20/-");
        jPanel5.add(jLabel12);
        jLabel12.setBounds(10, 190, 250, 40);

        jLabel13.setFont(new java.awt.Font("Calibri", 1, 30)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 0));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Coffee          60/-");
        jPanel5.add(jLabel13);
        jLabel13.setBounds(10, 110, 250, 30);

        jLabel14.setFont(new java.awt.Font("Calibri", 1, 30)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 0));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Noodle         50/-");
        jPanel5.add(jLabel14);
        jLabel14.setBounds(10, 140, 250, 30);

        jLabel15.setFont(new java.awt.Font("Calibri", 1, 30)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 0));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Chips            30/-");
        jPanel5.add(jLabel15);
        jLabel15.setBounds(10, 170, 250, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 35)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(254, 227, 152));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Food Prices");
        jLabel10.setToolTipText("");
        jPanel5.add(jLabel10);
        jLabel10.setBounds(10, 10, 250, 44);

        jPanel4.add(jPanel5);
        jPanel5.setBounds(0, 0, 270, 230);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(20, 500, 1045, 230);

        jPanel6.setBackground(new java.awt.Color(255, 255, 0));
        jPanel6.setPreferredSize(new java.awt.Dimension(340, 100));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Food Billing System");
        jLabel9.setPreferredSize(new java.awt.Dimension(400, 100));
        jPanel6.add(jLabel9);

        getContentPane().add(jPanel6);
        jPanel6.setBounds(20, 10, 940, 100);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b0ActionPerformed
        String EnterNumber = txtDisplay.getText() + b0.getText();
        txtDisplay.setText(EnterNumber);
    }//GEN-LAST:event_b0ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        String EnterNumber = txtDisplay.getText() + b1.getText();
        txtDisplay.setText(EnterNumber);
    }//GEN-LAST:event_b1ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        String EnterNumber = txtDisplay.getText() + b2.getText();
        txtDisplay.setText(EnterNumber);
    }//GEN-LAST:event_b2ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        String EnterNumber = txtDisplay.getText() + b3.getText();
        txtDisplay.setText(EnterNumber);
    }//GEN-LAST:event_b3ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
        String EnterNumber = txtDisplay.getText() + b4.getText();
        txtDisplay.setText(EnterNumber);
    }//GEN-LAST:event_b4ActionPerformed

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
        String EnterNumber = txtDisplay.getText() + b5.getText();
        txtDisplay.setText(EnterNumber);
    }//GEN-LAST:event_b5ActionPerformed

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
        String EnterNumber = txtDisplay.getText() + b6.getText();
        txtDisplay.setText(EnterNumber);
    }//GEN-LAST:event_b6ActionPerformed

    private void b7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b7ActionPerformed
        String EnterNumber = txtDisplay.getText() + b7.getText();
        txtDisplay.setText(EnterNumber);
    }//GEN-LAST:event_b7ActionPerformed

    private void b8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8ActionPerformed
        String EnterNumber = txtDisplay.getText() + b8.getText();
        txtDisplay.setText(EnterNumber);
    }//GEN-LAST:event_b8ActionPerformed

    private void b9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b9ActionPerformed
        String EnterNumber = txtDisplay.getText() + b9.getText();
        txtDisplay.setText(EnterNumber);
    }//GEN-LAST:event_b9ActionPerformed

    private void bdotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdotActionPerformed
        if(!txtDisplay.getText().contains("."))
        {
            txtDisplay.setText(txtDisplay.getText() + bdot.getText());
        }
    }//GEN-LAST:event_bdotActionPerformed

    private void baddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baddActionPerformed
        
        firstnum = Double.parseDouble(txtDisplay.getText());
        txtDisplay.setText("");
        operations = "+"; 
    }//GEN-LAST:event_baddActionPerformed

    private void bsubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsubActionPerformed
        firstnum = Double.parseDouble(txtDisplay.getText());
        txtDisplay.setText("");
        operations = "-"; 
    }//GEN-LAST:event_bsubActionPerformed

    private void bmulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bmulActionPerformed
        firstnum = Double.parseDouble(txtDisplay.getText());
        txtDisplay.setText("");
        operations = "*"; 
    }//GEN-LAST:event_bmulActionPerformed

    private void bdivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdivActionPerformed
        firstnum = Double.parseDouble(txtDisplay.getText());
        txtDisplay.setText("");
        operations = "/"; 
    }//GEN-LAST:event_bdivActionPerformed

    private void bmodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bmodActionPerformed
        firstnum = Double.parseDouble(txtDisplay.getText());
        txtDisplay.setText("");
        operations = "%"; 
    }//GEN-LAST:event_bmodActionPerformed

    private void bclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bclearActionPerformed
        txtDisplay.setText("");
    }//GEN-LAST:event_bclearActionPerformed

    private void bansActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bansActionPerformed
        secondnum = Double.parseDouble(txtDisplay.getText());
        
        if(operations == "+")
        {
            result = firstnum + secondnum;
            answers = String.format("%.2f",result);
            txtDisplay.setText(answers);
        }
        else if(operations == "-")
        {
            result = firstnum - secondnum;
            answers = String.format("%.2f",result);
            txtDisplay.setText(answers);
        }
        else if(operations == "*")
        {
            result = firstnum * secondnum;
            answers = String.format("%.2f",result);
            txtDisplay.setText(answers);
        }
        else if(operations == "/")
        {
            result = firstnum / secondnum;
            answers = String.format("%.2f",result);
            txtDisplay.setText(answers);
        }
        else
        {
            result = firstnum % secondnum;
            answers = String.format("%.2f",result);
            txtDisplay.setText(answers);
        }
            
    }//GEN-LAST:event_bansActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        txtDisplay.setText("");
        jTextField1.setText("0");
        jTextField2.setText("0");
        jTextField3.setText("0");
        jTextField4.setText("0");
        jTextField5.setText("0");
        jTextField6.setText("0");
        jTextField7.setText("0");
        jTextField8.setText("0");
        jTextField9.setText("0");
        jTextField10.setText("0");
        jTextField11.setText("Rs 0.0");
        jTextField12.setText("Rs 0.0");
        jTextField13.setText("Rs 0.0");
        
        jCheckBox1.setSelected(false);
        jCheckBox2.setSelected(false);
        jCheckBox3.setSelected(false);
        jCheckBox4.setSelected(false);
        jCheckBox5.setSelected(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        if(jCheckBox2.isSelected())
        {
            jTextField2.setEditable(true);
            jTextField2.setText("");
            jTextField2.requestFocus();
        }
        else
        {
            jTextField2.setEditable(false);
            jTextField2.setText("0");
        }
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
        if(jCheckBox3.isSelected())
        {
            jTextField3.setEditable(true);
            jTextField3.setText("");
            jTextField3.requestFocus();
        }
        else
        {
            jTextField3.setEditable(false);
            jTextField3.setText("0");
        }
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void jCheckBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox4ActionPerformed
        if(jCheckBox4.isSelected())
        {
            jTextField4.setEditable(true);
            jTextField4.setText("");
            jTextField4.requestFocus();
        }
        else
        {
            jTextField4.setEditable(false);
            jTextField4.setText("0");
        }
    }//GEN-LAST:event_jCheckBox4ActionPerformed

    private void jCheckBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox5ActionPerformed
        if(jCheckBox5.isSelected())
        {
            jTextField5.setEditable(true);
            jTextField5.setText("");
            jTextField5.requestFocus();
        }
        else
        {
            jTextField5.setEditable(false);
            jTextField5.setText("0");
        }
    }//GEN-LAST:event_jCheckBox5ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        if(jCheckBox1.isSelected())
        {
            jTextField1.setEditable(true);
            jTextField1.setText("");
            jTextField1.requestFocus();
        }
        else
        {
            jTextField1.setEditable(false);
            jTextField1.setText("0");
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if((jCheckBox1.isSelected()) || (jCheckBox2.isSelected()) || (jCheckBox3.isSelected()) || (jCheckBox4.isSelected()) || (jCheckBox5.isSelected()))
        {
            double f = Double.parseDouble(jTextField2.getText()) * 80;
            double v = Double.parseDouble(jTextField3.getText()) * 60;
            double p = Double.parseDouble(jTextField4.getText()) * 50;
            double w = Double.parseDouble(jTextField5.getText()) * 30;
            double b = Double.parseDouble(jTextField1.getText()) * 20;
            
            double totalitems = f + v + p + w + b;
            double del = totalitems * 5 / 100;
            double mil = del * 50 / 100;
            
            double subtotal = totalitems + del + mil;
            double cgst = subtotal * 9 / 100;
            double sgst = cgst + 10;
            
            double tax = cgst + sgst;
            
            double amount = subtotal + tax;
            
            String item = String.format("%.2f",totalitems);
            jTextField7.setText((String)item);
            
            String d = String.format("%.2f",del);
            jTextField8.setText((String)d);
            
            String m = String.format("%.2f",mil);
            jTextField9.setText((String)m);
            
            String c = String.format("%.2f",cgst);
            jTextField6.setText((String)c);
            
            String s = String.format("%.2f",sgst);
            jTextField10.setText((String)s);
            
            String sub = String.format("%.2f",subtotal);
            jTextField12.setText((String)sub);
            
            String ta = String.format("%.2f",tax);
            jTextField13.setText((String)ta);
            
            String tamount = String.format("%.2f",amount);
            jTextField11.setText((String)tamount);
        }
        else
        {
            txtDisplay.setText("Enter Choice");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        try {
            /* Set the Nimbus look and feel */
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
            UIManager.setLookAndFeel("com.jtattoo.plaf.aluminium.AluminiumLookAndFeel");
            
            /* Create and display the form */
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new BillingSystem().setVisible(true);
                }
            });
        } catch (ClassNotFoundException ex) {
              Logger.getLogger(BillingSystem.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
              Logger.getLogger(BillingSystem.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
              Logger.getLogger(BillingSystem.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
              Logger.getLogger(BillingSystem.class.getName()).log(Level.SEVERE, null, ex);
        }
        //</editor-fold>
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b0;
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JButton b8;
    private javax.swing.JButton b9;
    private javax.swing.JButton badd;
    private javax.swing.JButton bans;
    private javax.swing.JButton bclear;
    private javax.swing.JButton bdiv;
    private javax.swing.JButton bdot;
    private javax.swing.JButton bmod;
    private javax.swing.JButton bmul;
    private javax.swing.JButton bsub;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextField txtDisplay;
    // End of variables declaration//GEN-END:variables
}
